dkms-gentoo-12

diff --git a/dkms-gentoo/dkms-gentoo b/dkms-gentoo/dkms-gentoo
--- a/dkms-gentoo/dkms-gentoo
+++ b/dkms-gentoo/dkms-gentoo
@@ -7,6 +7,12 @@ DB="/var/db/pkg/"
 DKMS_TMP="/tmp/dkms_tmp"
 manual_ver="${2}"
 
+#colors
+green="\033[01;32m"
+red="\033[01;31m"
+restore="\033[00m"
+
+
 ##### check it!
 check(){
   if [ -z "${KERNEL}" ];then
@@ -15,16 +21,16 @@ check(){
   DKMS_FAILED="/var/log/dkms_failed-${KERNEL}"
 
   if [ -f "${DKMS_DB}" ];then
-  echo -e "\nTarget: \033[01;32m${KERNEL}\033[00m\n"
+  echo -e "\nTarget: ${green}${KERNEL}${restore}\n"
 	while read PKG MOD PKG_FILE;do
 
 	  if ! [ -f "${PKG_FILE}" ];then
-		echo -e "\n\033[01;31mDatabase incorrect!\033[00m\n"
+		echo -e "\n${red}Database incorrect!${restore} ---> file \"${green}${PKG_FILE}${restore}\" don't exists.\n"
 		VER="${PKG_FILE##*modules/}"
 		KERNEL="${VER%%/*}"
 		FAILED+=" ${PKG}"
 		BREAK="1"
-		echo -e "New target: \033[01;32m${KERNEL}\033[00m\n"
+		echo -e "New target: ${green}${KERNEL}${restore}\n"
 		break;
 	  fi
 
@@ -46,6 +52,11 @@ check(){
 	  fi
 	done < ${DKMS_DB}
 	rebuild_failed;
+	
+	if [ `readlink /usr/src/linux` != "linux-`uname -r`" ];then
+	  echo -e "\nSwitch symlink to: ${green}`uname -r`${restore} (loaded)\n"
+	  ln -sfT linux-`uname -r` /usr/src/linux
+	fi
   else
 	db_rebuild;
 	check;
@@ -76,16 +87,16 @@ db_rebuild(){
 	DKMS_TIMESTAMP="$(stat -c %Y ${DKMS_DB})"
 	DB_TIMESTAMP="$(stat -c %Y ${DB}*/ ${DB}*/*/ | sort | tail -n1)"
 	if (( "${DB_TIMESTAMP}" > "${DKMS_TIMESTAMP}" ));then
-	  echo "Database: updating"
-	  db_create
+	  echo -e "Database: ${green}updating...${restore}"
+	  db_create;
 	  eend $?
 	else
-	  echo "Database: already up-to-date."
+	  echo -e "Database: ${green}already up-to-date.${restore}"
 	  eend 0
 	fi
   else
-	echo "Database: creating"
-	db_create
+	echo -e "Database: ${green}creating...${restore}"
+	db_create;
 	eend $?
   fi
 }
@@ -94,16 +105,18 @@ db_rebuild(){
 rebuild_failed(){
   if [ -n "${FAILED}" ];then
 	FAILED_ATOMS="$(echo -e "${FAILED// /\n}" | sort -u)"
+	echo -e "Target packages: ${green}${FAILED_ATOMS}${restore}\n"
 	for ATOM in ${FAILED_ATOMS};do
 	  DB_PKG="$(find ${DB} -maxdepth 2 -name "${ATOM#*/}*")"
 	  echo "${ATOM} $(stat -c %Y $DB_PKG)" >> ${DKMS_TMP}
 	done
-	  eselect kernel set linux-${KERNEL}
+	  ln -sfT linux-${KERNEL} /usr/src/linux
 	  emerge -1 ${FAILED_ATOMS} \
 	  && rm -f "${DKMS_FAILED}" || \
 	  while read atom mtime;do
 		if (( "$(stat -c %Y ${DB_PKG})" == "${mtime}" ));then
 		  echo "${atom}" >> "${DKMS_FAILED}"
+		  exit 1;
 		fi
 	  done < ${DKMS_TMP}
 	rm -f ${DKMS_TMP}
@@ -114,9 +127,35 @@ rebuild_failed(){
   [ -n "${BREAK}" ] && unset BREAK KERNEL FAILED && check;
 }
 
+##### rebuild ALL modules for target kernel
+rebuild_all_mods() {
+  if [ -z "${KERNEL}" ];then
+	KERNEL="$(uname -r)"
+  fi
+  DKMS_FAILED="/var/log/dkms_failed-${KERNEL}"
+
+  if [ -f "${DKMS_DB}" ];then
+  echo -e "\nTarget: ${green}${KERNEL}${restore}\n"
+	while read PKG MOD PKG_FILE;do
+	  FAILED+=" ${PKG}"
+	done < ${DKMS_DB}
+	rebuild_failed;
+	echo -e "\nswitch symlink to loaded kernel.\n"
+	ln -sfT linux-`uname -r` /usr/src/linux
+  else
+	db_rebuild;
+	rebuild_all_mods;
+  fi
+}
+
 case ${1} in
 
---check ) check;;
+--check )
+  if [ -n "${manual_ver}" ];then
+	KERNEL="${manual_ver##*linux-}"
+	KERNEL="${KERNEL%/}"
+  fi
+  check;;
 
 --db ) db_rebuild;;
 
@@ -124,7 +163,7 @@ case ${1} in
   if [ -f "${DKMS_DB}" ];then
 	awk '{print $1,$2}' ${DKMS_DB} | column -t
   else
-	echo -e "database not found!\nYou need run:\ndkms-gentoo --db"
+	db_rebuild;
   fi;;
 
 --check-link ) build_symlink() {
@@ -134,21 +173,28 @@ case ${1} in
   }
   build_symlink;;
 
---check-manual ) manual() {
-  KERNEL="${manual_ver##*linux-}"
-  KERNEL="${KERNEL%/}"
-  check
-  }
-  manual;;
+--rebuild-all )
+  if [ -n "${manual_ver}" ];then
+	KERNEL="${manual_ver##*linux-}"
+	KERNEL="${KERNEL%/}"
+  fi
+  rebuild_all_mods;;
 
-* ) echo \
-"Usage: dkms-gentoo [OPTION]...[manual_only_VERSION]
+* ) echo -e \
+"Usage: dkms-gentoo [OPTION]… [TARGET]
 available options:
 
---db:           rebuild database.
---list:         display database.
---check:        check modules for loaded kernel.
---check-link:   check modules for symlinked kernel.
---check-manual: check modules for manualy selected kernel: version (i.e. 3.5.3-pf) or path to root of sources(i.e /usr/src/linux-3.5.6-pf/)";;
+--db:             rebuild database.
+--list:           display database.
+--check	[TARGET]: check modules for TARGET kernel.
+--check-link:     check modules for symlinked kernel.
+--rebuild-all:    rebuild all modules for TARGET kernel.
+
+TARGET can be one of:
+
+\t[version]: example '3.5.3-pf'
+\t[PATH]:    example '/usr/src/linux-3.5.6-pf/'
+
+else TARGET=='`uname -r`' (loaded)";;
 
 esac
